services:
  app:
    build: .
    command: bundle exec middleman server --port 4000 --bind-address '0.0.0.0'
    container_name: nothub.org
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "4000:4000"
    environment:
      BUNDLE_PATH: /bundle

volumes:
  bundle:
