version: '3'
services:
  app:
    build: .
    command: bash -c "bundle exec middleman server -p 4000 -b '0.0.0.0'"
    container_name: nothub.org
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "4000:4000"
    environment:
      BUNDLE_PATH: /bundle

volumes:
  bundle:
