name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ruby:3.2.1
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: Setup & Build
      run: |
        bundle exec rake setup build
      if: github.ref != 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
    - name: Publish
      run: |
        bundle exec rake setup build publish
      if: github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: Ryunosuke Sato
        GIT_AUTHOR_EMAIL: tricknotes.rs@gmail.com
        GIT_COMMITTER_NAME: Ryunosuke Sato
        GIT_COMMITTER_EMAIL: tricknotes.rs@gmail.com
